const data = {
    products: [
        {
            _id: 1,
            name: 'Programmer Hoodie',
            cathegory: 'Hoodies',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Sean',
            rating: 4.5,
            numReviews: 10,
            desciption: 'hight quality product',
        },
        {
            _id: 2,
            name: 'Programmer shirt',
            cathegory: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Unknown',
            rating: 4.6,
            numReviews: 38,
            desciption: 'hight quality product',
        },
        {
            _id: 3,
            name: 'Programmer gap',
            cathegory: 'Gaps',
            image: '/images/p3.jpg',
            price: 50,
            brand: 'Adidas',
            rating: 4,
            numReviews: 5,
            desciption: 'hight quality product',
        },
        {
            _id: 4,
            name: 'Blue jeans',
            cathegory: 'Jeans',
            image: '/images/p4.jpg',
            price: 150,
            brand: 'Vans',
            rating: 4.8,
            numReviews: 15,
            desciption: 'hight quality product',
        },
        {
            _id: 5,
            name: 'Hey Arnold hoodie',
            cathegory: 'Hoodies',
            image: '/images/p5.jpg',
            price: 200,
            brand: 'DC',
            rating: 4.9,
            numReviews: 20,
            desciption: 'hight quality product',
        },
        {
            _id: 6,
            name: 'Skate shoes',
            cathegory: 'Shoes',
            image: '/images/p6.jpg',
            price: 180,
            brand: 'Vans',
            rating: 4,
            numReviews: 2,
            desciption: 'hight quality product',
        },
    ],
};
//hello anxiety;
export default data;